included:
  - Sources
  - Tests

nesting:
  type_level: 2

opt_in_rules:
  - closure_end_indentation
  - empty_count
  - force_unwrapping
  - literal_expression_end_indentation

force_cast: error
force_try: error
force_unwrapping: error

line_length: 120

identifier_name:
  excluded:
    - id
    - db

closure_end_indentation: error

reporter: "emoji"