version: 2

jobs:
  macos-4.1:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run:
          name: Install LibreSSL
          command: brew install libressl
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  macos-release-4.1:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run:
          name: Install LibreSSL
          command: brew install libressl
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  macos-4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install LibreSSL
          command: brew install libressl
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  macos-release-4.2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install LibreSSL
          command: brew install libressl
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  linux-4.1:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release-4.1:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  linux-4.2:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test

  linux-release-4.2:
    docker:
      - image: swift:4.2
    steps:
      - checkout
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  swiftlint:
    docker:
      - image: norionomura/swiftlint
    steps:
      - checkout
      - run: swiftlint

workflows:
  version: 2
  tests:
    jobs:
      - swiftlint
      - linux-4.1
      - linux-release-4.1
      - macos-4.1
      - macos-release-4.1
      - linux-4.2
      - linux-release-4.2
      - macos-4.2
      - macos-release-4.2

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux-4.1
      - linux-release-4.1
      - macos-4.1
      - macos-release-4.1
      - linux-4.2
      - linux-release-4.2
      - macos-4.2
      - macos-release-4.2
